module.exports = [{
  defined_break_time_mins: 60,
  defined_clockin_adjustment_enabled: false,
  defined_clockin_time_buffer_mins: 30,
  defined_clockin_time_hour: 9,
  defined_clockin_time_late_enabled: true,
  defined_clockin_time_min: 0,
  defined_clockout_adjustment_enabled: false,
  defined_clockout_time_buffer_mins: 30,
  defined_clockout_time_early_leave_enabled: true,
  defined_clockout_time_hour: 18,
  defined_clockout_time_min: 0,
  defined_overtime_enabled: false,
  defined_overtime_minimum_min: 0,
  defined_overtime_time_hour: 19,
  defined_overtime_time_min: 0,
  specified_holidays: [],
  specified_non_holidays: [],
  video_device_group_in: [],
  video_device_group_out: [],
}];
